#!/usr/bin/env bash
# Join the two toolchains: ReXGlue analysis -> a ready XenonRecomp config tree.
#
#   xenon_export.sh <port-dir> <target-tree> <NAME>
#   xenon_export.sh ~/recomp-ports/geometrywars2-recomp ~/gw2-xenon GW2
#
# ReXGlue's codegen already emits <slug>_xenonrecomp.toml and
# <slug>_switch_tables.toml on every run (codegen_writer.cpp). Turning those
# into a buildable XenonRecomp tree was the one step in the whole pipeline with
# no script - somebody hand-copied them, renamed them, and hand-wrote the
# [main] block, the setjmp/longjmp addresses and the optimisation flags. This
# does that.
#
# Why the join exists at all: XenonRecomp's README gives up on both of the hard
# analysis problems - jump tables ("there is currently no solution for this")
# and the register save/restore helpers ("no mechanism for it"). ReXGlue solves
# both, and its phase_validate refuses to emit a line of code while any branch
# target is unresolved, so a port that builds has every boundary proven rather
# than guessed.
set -uo pipefail

PORT="${1:?usage: xenon_export.sh <port-dir> <target-tree> <NAME>}"
TREE="${2:?usage: xenon_export.sh <port-dir> <target-tree> <NAME>}"
NAME="${3:?usage: xenon_export.sh <port-dir> <target-tree> <NAME>}"
SDK="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)"

SLUG="$(basename "$PORT")"; SLUG="${SLUG%-recomp}"
GEN="$PORT/generated/default"
FN_SRC="$GEN/${SLUG}_xenonrecomp.toml"
SW_SRC="$GEN/${SLUG}_switch_tables.toml"

for f in "$FN_SRC" "$SW_SRC"; do
  [ -f "$f" ] || { echo "missing $f - run 'rexglue codegen' in $PORT first" >&2; exit 2; }
done

XEX="$TREE/private/default.xex"
[ -f "$XEX" ] || { echo "no XEX at $XEX" >&2; exit 2; }

mkdir -p "$TREE/config"
OUT="$TREE/config/$NAME.toml"

# setjmp/longjmp must be declared BEFORE the first build. Undeclared, XenonRecomp
# emits the longjmp body as an ordinary call: control never unwinds, the caller
# carries on with non-volatiles from a stale jmp_buf, and the title renders
# nothing for reasons that surface nowhere near the cause. It cost both Geometry
# Wars titles a black screen.
SETJMP=""; LONGJMP=""
# First choice: whatever this tree already had. find_setjmp.py scans a decrypted
# image and returns nothing for a raw XEX, so a previously-found pair is better
# evidence than a fresh failed scan - and silently dropping it on a re-export
# would turn a working tree into a black screen.
if [ -f "$OUT" ]; then
  SETJMP=$(sed -nE 's/^setjmp_address *= *(0x[0-9A-Fa-f]+).*/\1/p'  "$OUT" | head -1)
  LONGJMP=$(sed -nE 's/^longjmp_address *= *(0x[0-9A-Fa-f]+).*/\1/p' "$OUT" | head -1)
  [ -n "$SETJMP" ] && echo "  reusing setjmp/longjmp from the existing $NAME.toml"
fi
if [ -z "$SETJMP" ] && [ -f "$SDK/tools/find_setjmp.py" ]; then
  eval "$(python3 "$SDK/tools/find_setjmp.py" "$XEX" 2>/dev/null \
          | sed -nE 's/.*setjmp[^0-9a-fx]*(0x[0-9A-Fa-f]+).*/SETJMP=\1/p; s/.*longjmp[^0-9a-fx]*(0x[0-9A-Fa-f]+).*/LONGJMP=\1/p')" || true
fi

{
  echo "# $NAME - XenonRecomp configuration."
  echo "#"
  echo "# Generated by tools/xenon_export.sh from ReXGlue's analysis of"
  echo "# $SLUG. The function boundaries and ABI helper addresses below were not"
  echo "# found by XenonAnalyse - ReXGlue discovers them and refuses to emit code"
  echo "# while any branch target is unresolved, so every boundary here is proven."
  echo "# Re-run that script rather than editing this file by hand."
  echo
  echo '[main]'
  echo 'file_path = "../private/default.xex"'
  echo 'out_directory_path = "../ppc"'
  echo "switch_table_file_path = \"${NAME}_switch_tables.toml\""
  echo
  echo "# Left off until there is a running recompilation, as XenonRecomp's README"
  echo "# advises. non_volatile_as_local is worth ~9% of profile samples when it"
  echo "# works and shredded every frame on Burnout Revenge; earn it back per title."
  for f in skip_lr skip_msr ctr_as_local xer_as_local reserved_as_local \
           cr_as_local non_argument_as_local non_volatile_as_local; do
    echo "$f = false"
  done
  echo
  if [ -n "$LONGJMP" ] && [ -n "$SETJMP" ]; then
    echo "longjmp_address = $LONGJMP"
    echo "setjmp_address = $SETJMP"
  else
    echo "# WARNING: setjmp/longjmp NOT detected - find them and add them before"
    echo "# the first build, or the title will render nothing."
    echo "# longjmp_address = 0x0"
    echo "# setjmp_address = 0x0"
  fi
  echo
  cat "$FN_SRC"
} > "$OUT"

cp "$SW_SRC" "$TREE/config/${NAME}_switch_tables.toml"

FNS=$(grep -c '{ address' "$OUT" || echo 0)
SWS=$(grep -c '^\[\[switch\]\]' "$TREE/config/${NAME}_switch_tables.toml" || echo 0)

echo "wrote $OUT"
echo "  functions     $FNS"
echo "  switch tables $SWS"
if [ -z "$LONGJMP" ] || [ -z "$SETJMP" ]; then
  echo "  setjmp/longjmp NOT FOUND - fix before building (see the warning in the file)"
  exit 1
fi
echo "  longjmp $LONGJMP  setjmp $SETJMP"
echo
echo "next: XenonRecomp $OUT <XenonUtils/ppc_context.h>"
